name: coveralls
version: 4.0.0

author: Cédric Belin <cedric@belin.io>
description: Send LCOV and Clover coverage reports to the Coveralls service.
documentation: https://dev.belin.io/coveralls.dart/api
homepage: https://dev.belin.io/coveralls.dart

environment:
  sdk: '>=2.0.0 <3.0.0'

executables:
  coveralls: coveralls

dependencies:
  build_cli_annotations: ^1.0.0
  crypto: ^2.0.6
  http: ^0.11.3
  json_annotation: ^1.1.0
  lcov: ^4.3.0
  path: ^1.6.2
  pubspec_parse: ^0.1.2
  where: ^4.3.1
  xml: ^3.2.0
  yaml: ^2.1.15

dev_dependencies:
  build_cli: ^1.0.0
  build_runner: ^0.10.1
  build_test: ^0.10.3
  coverage: ^0.12.2
  grinder: ^0.8.3
  json_serializable: ^1.2.1
  test: ^1.3.0
