name: coveralls
version: 5.7.0

description: Send LCOV and Clover coverage reports to the Coveralls service.
homepage: https://dev.belin.io/coveralls.dart
issue_tracker: https://github.com/cedx/coveralls.dart/issues
repository: https://github.com/cedx/coveralls.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

executables:
  coveralls: coveralls

dependencies:
  build_cli_annotations: ^1.1.0
  crypto: ^2.1.4
  http: ^0.12.0
  json_annotation: ^3.0.1
  lcov: ^5.6.0
  path: ^1.6.4
  where: ^6.6.0
  xml: ^3.7.0
  yaml: ^2.2.0

dev_dependencies:
  build_cli: ^1.3.6
  build_runner: ^1.8.0
  build_test: ^0.10.12
  build_version: ^2.0.1
  coverage: ^0.13.9
  grinder: ^0.8.3
  json_serializable: ^3.2.5
  test: ^1.14.2
