name: coveralls
version: 5.10.0

description: Send LCOV and Clover coverage reports to the Coveralls service.
homepage: https://docs.belin.io/coveralls.dart
issue_tracker: https://git.belin.io/cedx/coveralls.dart/issues
repository: https://git.belin.io/cedx/coveralls.dart

environment:
  sdk: ">=2.10.0 <3.0.0"

executables:
  coveralls: coveralls

dependencies:
  build_cli_annotations: ^1.2.0
  crypto: ^2.1.5
  http: ^0.12.2
  json_annotation: ^3.1.1
  lcov: ^6.0.0
  path: ^1.7.0
  where: ^8.0.0
  xml: ^4.5.1
  yaml: ^2.2.1

dev_dependencies:
  build_cli: ^1.3.10
  build_runner: ^1.11.0
  build_test: ^1.3.4
  build_version: ^2.0.1
  coverage: ^0.14.2
  json_serializable: ^3.5.1
  test: ^1.15.7
