name: coveralls
version: 3.1.0

author: Cédric Belin <cedric@belin.io>
description: Send LCOV and Clover coverage reports to the Coveralls service.
documentation: https://dev.belin.io/coveralls.dart/api
homepage: https://dev.belin.io/coveralls.dart

environment:
  sdk: '>=2.0.0-dev.64 <2.0.0'

executables:
  coveralls: coveralls

dependencies:
  args: ^1.4.3
  crypto: ^2.0.5
  http: ^0.11.3
  lcov: ^4.1.0
  path: ^1.6.1
  where: ^4.1.0
  xml: ^3.0.0
  yaml: ^2.1.14

dev_dependencies:
  coverage: ^0.12.1
  grinder: ^0.8.2
  test: ^1.0.0
