name: coveralls
version: 5.0.0

author: Cédric Belin <cedric@belin.io>
description: Send LCOV and Clover coverage reports to the Coveralls service.
documentation: https://dev.belin.io/coveralls.dart/api
homepage: https://dev.belin.io/coveralls.dart

environment:
  sdk: '>=2.1.0 <3.0.0'

executables:
  coveralls: coveralls

dependencies:
  build_cli_annotations: ^1.0.1
  crypto: ^2.0.6
  http: ^0.12.0
  json_annotation: ^2.0.0
  lcov: ^5.0.0
  path: ^1.6.2
  where: ^6.0.0
  xml: ^3.2.3
  yaml: ^2.1.15

dev_dependencies:
  build_cli: ^1.0.2
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_version: ^2.0.0
  coverage: ^0.12.3
  grinder: ^0.8.3
  json_serializable: ^2.0.0
  test: ^1.5.1
