name: coveralls
version: 3.0.0

author: Cédric Belin <cedric@belin.io>
description: Send LCOV and Clover coverage reports to the Coveralls service.
documentation: https://cedx.github.io/coveralls.dart
homepage: https://github.com/cedx/coveralls.dart

environment:
  sdk: '>=2.0.0-dev <2.0.0'

executables:
  coveralls: coveralls

dependencies:
  args: ^1.4.2
  crypto: ^2.0.2
  file: ^5.0.0
  http: ^0.11.3
  lcov: ^4.1.0
  nodejs_interop: ^0.10.0
  platform: ^2.1.2
  process: ^3.0.1
  where: ^4.0.1
  xml: ^3.0.0
  yaml: ^2.1.13

dependency_overrides:
  nodejs_interop:
    path: ../nodejs-interop.dart
  where:
    path: ../where.dart

dev_dependencies:
  coverage: ^0.11.0
  node_preamble: ^1.4.0
  grinder: ^0.8.1
  test: ^0.12.34
