name: coveralls
version: 5.10.0

description: Send LCOV and Clover coverage reports to the Coveralls service.
homepage: https://cedx.github.io/coveralls.dart
issue_tracker: https://github.com/cedx/coveralls.dart/issues
repository: https://github.com/cedx/coveralls.dart

authors:
  - https://cedx.github.io/coveralls.dart
  - GiKode <827266641@qq.com>

environment:
  sdk: ">=2.13.0 <3.0.0"

executables:
  coveralls: coveralls

dependencies:
  build_cli_annotations: ^2.0.0
  crypto: ^3.0.1
  http: ^0.13.3
  json_annotation: ^4.0.1
  lcov:
    git:
      url: https://github.com/AugustToko/lcov.dart.git
  path: ^1.8.0
  where:
    git:
      url: https://github.com/AugustToko/where.dart.git
  xml: ^5.1.1
  yaml: ^3.1.0

dev_dependencies:
  build_cli: ^2.1.2
  build_runner: ^2.0.4
  build_test: ^2.0.4
  build_version: ^2.0.3
  coverage: ^1.0.3
  json_serializable: ^4.1.3
  test: ^1.17.5
