name: coveralls
version: 5.1.0

author: Cédric Belin <cedric@belin.io>
description: Send LCOV and Clover coverage reports to the Coveralls service.
documentation: https://dev.belin.io/coveralls.dart/api
homepage: https://dev.belin.io/coveralls.dart
issue_tracker: https://github.com/cedx/coveralls.dart/issues
repository: https://github.com/cedx/coveralls.dart

environment:
  sdk: '>=2.2.0 <3.0.0'

executables:
  coveralls: coveralls

dependencies:
  build_cli_annotations: ^1.0.1
  crypto: ^2.0.6
  http: ^0.12.0
  json_annotation: ^2.0.0
  lcov: ^5.1.0
  path: ^1.6.2
  where: ^6.1.0
  xml: ^3.4.0
  yaml: ^2.1.15

dev_dependencies:
  build_cli: ^1.2.2
  build_runner: ^1.2.8
  build_test: ^0.10.6
  build_version: ^2.0.0
  coverage: ^0.12.4
  grinder: ^0.8.3
  json_serializable: ^2.0.2
  test: ^1.5.3
