name: coveralls
version: 5.4.0

author: Cédric Belin <cedric@belin.io>
description: Send LCOV and Clover coverage reports to the Coveralls service.
documentation: https://dev.belin.io/coveralls.dart/api
homepage: https://dev.belin.io/coveralls.dart
issue_tracker: https://github.com/cedx/coveralls.dart/issues
repository: https://github.com/cedx/coveralls.dart

environment:
  sdk: '>=2.4.0 <3.0.0'

executables:
  coveralls: coveralls

dependencies:
  build_cli_annotations: ^1.1.0
  crypto: ^2.1.2
  http: ^0.12.0
  json_annotation: ^3.0.0
  lcov: ^5.4.0
  path: ^1.6.4
  where: ^6.4.0
  xml: ^3.5.0
  yaml: ^2.1.16

dev_dependencies:
  build_cli: ^1.3.4
  build_runner: ^1.6.8
  build_test: ^0.10.8
  build_version: ^2.0.1
  coverage: ^0.13.2
  grinder: ^0.8.3
  json_serializable: ^3.2.2
  test: ^1.6.9
