name: coveralls
version: 0.1.0

author: Cédric Belin <cedric@belin.io>
description: Send LCOV coverage reports to the Coveralls service.
documentation: https://cedx.github.io/coveralls.dart
homepage: https://github.com/cedx/coveralls.dart

environment:
  sdk: '>=1.21.0 <2.0.0'

executables:
  coveralls: coveralls

dependencies:
  args: ^0.13.7
  http: ^0.11.3
  lcov: ^0.3.0
  yaml: ^2.1.12

dev_dependencies:
  grinder: ^0.8.0
  test: ^0.12.18
