name: coveralls
version: 5.3.0

author: Cédric Belin <cedric@belin.io>
description: Send LCOV and Clover coverage reports to the Coveralls service.
documentation: https://dev.belin.io/coveralls.dart/api
homepage: https://dev.belin.io/coveralls.dart
issue_tracker: https://github.com/cedx/coveralls.dart/issues
repository: https://github.com/cedx/coveralls.dart

environment:
  sdk: '>=2.3.0 <3.0.0'

executables:
  coveralls: coveralls

dependencies:
  build_cli_annotations: ^1.1.0
  crypto: ^2.0.6
  http: ^0.12.0
  json_annotation: ^2.4.0
  lcov: ^5.3.0
  path: ^1.6.2
  where: ^6.3.0
  xml: ^3.5.0
  yaml: ^2.1.15

dev_dependencies:
  build_cli: ^1.3.2
  build_runner: ^1.5.0
  build_test: ^0.10.7
  build_version: ^2.0.1
  coverage: ^0.12.4
  grinder: ^0.8.3
  json_serializable: ^3.0.0
  test: ^1.6.3
