name: coveralls
version: 3.2.0

author: Cédric Belin <cedric@belin.io>
description: Send LCOV and Clover coverage reports to the Coveralls service.
documentation: https://dev.belin.io/coveralls.dart/api
homepage: https://dev.belin.io/coveralls.dart

environment:
  sdk: '>=2.0.0-dev.69 <3.0.0'

executables:
  coveralls: coveralls

dependencies:
  build_cli_annotations: ^0.1.2
  crypto: ^2.0.6
  http: ^0.11.3
  json_annotation: ^1.0.0
  lcov: ^4.2.0
  path: ^1.6.2
  pubspec_parse: ^0.1.2
  where: ^4.2.0 # ^4.3.0
  xml: ^3.2.0
  yaml: ^2.1.15

dev_dependencies:
  build_cli: ^0.2.5
  build_runner: ^0.10.0
  coverage: ^0.12.2
  grinder: ^0.8.3
  json_serializable: ^1.0.0
  test: ^1.3.0
