name: coveralls
version: 3.0.0

author: Cédric Belin <cedric@belin.io>
description: Send LCOV and Clover coverage reports to the Coveralls service.
documentation: https://cedx.github.io/coveralls.dart
homepage: https://github.com/cedx/coveralls.dart

environment:
  sdk: '>=1.24.0 <2.0.0'

executables:
  coveralls: coveralls

dependencies:
  args: ^1.2.0
  crypto: ^2.0.2
  file: ^2.3.5
  http: ^0.11.3
  lcov: ^3.1.0
  nodejs_interop: ^0.8.0
  platform: ^2.1.1
  process: ^2.0.8
  where: ^3.1.0
  xml: ^2.6.0
  yaml: ^2.1.13

dependency_overrides:
  nodejs_interop:
    path: ../nodejs-interop.dart
  where:
    path: ../where.dart

dev_dependencies:
  coverage: ^0.10.0
  node_preamble: ^1.4.0
  grinder: ^0.8.1
  test: ^0.12.32
