name: coveralls
version: 0.1.0

author: Cédric Belin <cedric@belin.io>
description: Send coverage reports to the Coveralls service.
documentation: https://cedx.github.io/coveralls.dart
homepage: https://github.com/cedx/coveralls.dart

environment:
  sdk: '>=1.21.0 <2.0.0'

dependencies:
  http: ^0.11.3
  lcov: ^0.1.0

dev_dependencies:
  grinder: ^0.8.0
  test: ^0.12.18
